export default [
  {
    id: 1,
    codepays: 'US',
    nom: 'Etats-Unis',
    indicatif: '1',
    devise: 2,
  },
  {
    id: 2,
    codepays: 'AD',
    nom: 'Andorre',
    indicatif: '376',
    devise: 4,
  },
  {
    id: 3,
    codepays: 'FR',
    nom: 'France',
    indicatif: '33',
    devise: 4,
  },
  {
    id: 4,
    codepays: 'DE',
    nom: 'Allemagne',
    indicatif: '49',
    devise: 4,
  },
  {
    id: 5,
    codepays: 'IE',
    nom: 'Irlande',
    indicatif: '353',
    devise: 4,
  },
  {
    id: 6,
    codepays: 'GH',
    nom: 'Ghana',
    indicatif: '233',
    devise: 6,
  },
  {
    id: 7,
    codepays: 'KE',
    nom: 'Kenya',
    indicatif: '254',
    devise: 7,
  },
  {
    id: 8,
    codepays: 'ZA',
    nom: 'Afrique du Sud',
    indicatif: '27',
    devise: 10,
  },
  {
    id: 9,
    codepays: 'CM',
    nom: 'Cameroun',
    indicatif: '237',
    devise: 5,
  },
  {
    id: 10,
    codepays: 'CG',
    nom: 'Congo',
    indicatif: '242',
    devise: 5,
  },
  {
    id: 11,
    codepays: 'GA',
    nom: 'Gabon',
    indicatif: '241',
    devise: 5,
  },
  {
    id: 12,
    codepays: 'BF',
    nom: 'Burkina Faso',
    indicatif: '226',
    devise: 1,
  },
  {
    id: 13,
    codepays: 'CI',
    nom: 'Côte d\'Ivoire',
    indicatif: '225',
    devise: 1,
  },
  {
    id: 14,
    codepays: 'ML',
    nom: 'Mali',
    indicatif: '223',
    devise: 1,
  },
  {
    id: 15,
    codepays: 'SN',
    nom: 'Sénégal',
    indicatif: '221',
    devise: 1,
  },
  {
    id: 16,
    codepays: 'TW',
    nom: 'Taiwan',
    indicatif: '886',
    devise: 2,
  },
  {
    id: 17,
    codepays: 'AF',
    nom: 'Afghanistan',
    indicatif: '93',
    devise: 2,
  },
  {
    id: 18,
    codepays: 'AL',
    nom: 'Albanie',
    indicatif: '355',
    devise: 2,
  },
  {
    id: 19,
    codepays: 'DZ',
    nom: 'Algérie',
    indicatif: '213',
    devise: 2,
  },
  {
    id: 20,
    codepays: 'AO',
    nom: 'Angola',
    indicatif: '244',
    devise: 2,
  },
  {
    id: 21,
    codepays: 'AQ',
    nom: 'Antarctique',
    indicatif: '10000',
    devise: 2,
  },
  {
    id: 22,
    codepays: 'AN',
    nom: 'Antilles néerlandaises',
    indicatif: '599',
    devise: 2,
  },
  {
    id: 23,
    codepays: 'KH',
    nom: 'Cambodge',
    indicatif: '855',
    devise: 2,
  },
  {
    id: 24,
    codepays: 'EC',
    nom: 'Equateur',
    indicatif: '593',
    devise: 2,
  },
  {
    id: 25,
    codepays: 'FM',
    nom: 'Micronésie',
    indicatif: '691',
    devise: 2,
  },
  {
    id: 26,
    codepays: 'PW',
    nom: 'Belau',
    indicatif: '10001',
    devise: 2,
  },
  {
    id: 27,
    codepays: 'CA',
    nom: 'Canada',
    indicatif: '1997',
    devise: 3,
  },
  {
    id: 28,
    codepays: 'AT',
    nom: 'Autriche',
    indicatif: '43',
    devise: 4,
  },
  {
    id: 29,
    codepays: 'BE',
    nom: 'Belgique',
    indicatif: '32',
    devise: 4,
  },
  {
    id: 30,
    codepays: 'CY',
    nom: 'Chypre',
    indicatif: '357',
    devise: 4,
  },
  {
    id: 31,
    codepays: 'EE',
    nom: 'Estonie',
    indicatif: '372',
    devise: 4,
  },
  {
    id: 32,
    codepays: 'FI',
    nom: 'Finlande',
    indicatif: '358',
    devise: 4,
  },
  {
    id: 33,
    codepays: 'GF',
    nom: 'Guyane française',
    indicatif: '594',
    devise: 4,
  },
  {
    id: 34,
    codepays: 'GR',
    nom: 'Grèce',
    indicatif: '30',
    devise: 4,
  },
  {
    id: 35,
    codepays: 'GP',
    nom: 'Guadeloupe',
    indicatif: '590',
    devise: 4,
  },
  {
    id: 36,
    codepays: 'IT',
    nom: 'Italie',
    indicatif: '39',
    devise: 4,
  },
  {
    id: 37,
    codepays: 'LV',
    nom: 'Lettonie',
    indicatif: '371',
    devise: 4,
  },
  {
    id: 38,
    codepays: 'LT',
    nom: 'Lituanie',
    indicatif: '370',
    devise: 4,
  },
  {
    id: 39,
    codepays: 'LU',
    nom: 'Luxembourg',
    indicatif: '352',
    devise: 4,
  },
  {
    id: 40,
    codepays: 'MT',
    nom: 'Malte',
    indicatif: '356',
    devise: 4,
  },
  {
    id: 41,
    codepays: 'MQ',
    nom: 'Martinique',
    indicatif: '596',
    devise: 4,
  },
  {
    id: 42,
    codepays: 'YT',
    nom: 'Mayotte',
    indicatif: '269',
    devise: 4,
  },
  {
    id: 43,
    codepays: 'MC',
    nom: 'Monaco',
    indicatif: '377',
    devise: 4,
  },
  {
    id: 44,
    codepays: 'SK',
    nom: 'Slovaquie',
    indicatif: '421',
    devise: 4,
  },
  {
    id: 45,
    codepays: 'SI',
    nom: 'Slovénie',
    indicatif: '386',
    devise: 4,
  },
  {
    id: 46,
    codepays: 'ES',
    nom: 'Espagne',
    indicatif: '34',
    devise: 4,
  },
  {
    id: 47,
    codepays: 'NG',
    nom: 'Nigeria',
    indicatif: '234',
    devise: 9,
  },
  {
    id: 48,
    codepays: 'LS',
    nom: 'Lesotho',
    indicatif: '266',
    devise: 10,
  },
  {
    id: 49,
    codepays: 'NA',
    nom: 'Namibie',
    indicatif: '264',
    devise: 10,
  },
  {
    id: 50,
    codepays: 'CD',
    nom: 'Republique Democratique du Congo',
    indicatif: '243',
    devise: 8,
  },
  {
    id: 51,
    codepays: 'CF',
    nom: 'Centrafique',
    indicatif: '236',
    devise: 5,
  },
  {
    id: 52,
    codepays: 'GQ',
    nom: 'Guinée Equatoriale',
    indicatif: '240',
    devise: 5,
  },
  {
    id: 53,
    codepays: 'BJ',
    nom: 'Bénin',
    indicatif: '229',
    devise: 1,
  },
  {
    id: 54,
    codepays: 'GW',
    nom: 'Guinée-Bissau',
    indicatif: '245',
    devise: 1,
  },
  {
    id: 55,
    codepays: 'NE',
    nom: 'Niger',
    indicatif: '227',
    devise: 1,
  },
  {
    id: 56,
    codepays: 'TG',
    nom: 'Togo',
    indicatif: '228',
    devise: 1,
  },
  {
    id: 57,
    codepays: 'SG',
    nom: 'Singapour',
    indicatif: '65',
    devise: 2,
  },
  {
    id: 58,
    codepays: 'SA',
    nom: 'Arabie saoudite',
    indicatif: '966',
    devise: 2,
  },
  {
    id: 59,
    codepays: 'AR',
    nom: 'Argentine',
    indicatif: '54',
    devise: 2,
  },
  {
    id: 60,
    codepays: 'AM',
    nom: 'Arménie',
    indicatif: '374',
    devise: 2,
  },
  {
    id: 61,
    codepays: 'AW',
    nom: 'Aruba',
    indicatif: '297',
    devise: 2,
  },
  {
    id: 62,
    codepays: 'AU',
    nom: 'Australie',
    indicatif: '61',
    devise: 2,
  },
  {
    id: 63,
    codepays: 'BH',
    nom: 'Bahreïn',
    indicatif: '973',
    devise: 2,
  },
  {
    id: 64,
    codepays: 'BD',
    nom: 'Bangladesh',
    indicatif: '880',
    devise: 2,
  },
  {
    id: 65,
    codepays: 'BZ',
    nom: 'Belize',
    indicatif: '501',
    devise: 2,
  },
  {
    id: 66,
    codepays: 'BT',
    nom: 'Bhoutan',
    indicatif: '975',
    devise: 2,
  },
  {
    id: 67,
    codepays: 'BY',
    nom: 'Biélorussie',
    indicatif: '375',
    devise: 2,
  },
  {
    id: 68,
    codepays: 'MM',
    nom: 'Birmanie',
    indicatif: '95',
    devise: 2,
  },
  {
    id: 69,
    codepays: 'BO',
    nom: 'Bolivie',
    indicatif: '591',
    devise: 2,
  },
  {
    id: 70,
    codepays: 'BA',
    nom: 'Bosnie-Herzégovine',
    indicatif: '387',
    devise: 2,
  },
  {
    id: 71,
    codepays: 'BW',
    nom: 'Botswana',
    indicatif: '267',
    devise: 2,
  },
  {
    id: 72,
    codepays: 'BR',
    nom: 'Brésil',
    indicatif: '55',
    devise: 2,
  },
  {
    id: 73,
    codepays: 'BN',
    nom: 'Brunei',
    indicatif: '673',
    devise: 2,
  },
  {
    id: 74,
    codepays: 'BG',
    nom: 'Bulgarie',
    indicatif: '359',
    devise: 2,
  },
  {
    id: 75,
    codepays: 'BI',
    nom: 'Burundi',
    indicatif: '257',
    devise: 2,
  },
  {
    id: 76,
    codepays: 'CV',
    nom: 'Cap-Vert',
    indicatif: '238',
    devise: 2,
  },
  {
    id: 77,
    codepays: 'CL',
    nom: 'Chili',
    indicatif: '56',
    devise: 2,
  },
  {
    id: 78,
    codepays: 'CN',
    nom: 'Chine',
    indicatif: '86',
    devise: 2,
  },
  {
    id: 79,
    codepays: 'CO',
    nom: 'Colombie',
    indicatif: '57',
    devise: 2,
  },
  {
    id: 80,
    codepays: 'KM',
    nom: 'Comores',
    indicatif: '269',
    devise: 2,
  },
  {
    id: 81,
    codepays: 'KP',
    nom: 'Corée du Nord',
    indicatif: '850',
    devise: 2,
  },
  {
    id: 82,
    codepays: 'KR',
    nom: 'Corée du Sud',
    indicatif: '82',
    devise: 2,
  },
  {
    id: 83,
    codepays: 'CR',
    nom: 'Costa Rica',
    indicatif: '506',
    devise: 2,
  },
  {
    id: 84,
    codepays: 'HR',
    nom: 'Croatie',
    indicatif: '385',
    devise: 2,
  },
  {
    id: 85,
    codepays: 'CU',
    nom: 'Cuba',
    indicatif: '53',
    devise: 2,
  },
  {
    id: 86,
    codepays: 'DK',
    nom: 'Danemark',
    indicatif: '45',
    devise: 2,
  },
  {
    id: 87,
    codepays: 'DJ',
    nom: 'Djibouti',
    indicatif: '253',
    devise: 2,
  },
  {
    id: 88,
    codepays: 'EG',
    nom: 'Egypte',
    indicatif: '20',
    devise: 2,
  },
  {
    id: 89,
    codepays: 'AE',
    nom: 'Emirats arabes unis',
    indicatif: '971',
    devise: 2,
  },
  {
    id: 90,
    codepays: 'ER',
    nom: 'Erythrée',
    indicatif: '291',
    devise: 2,
  },
  {
    id: 91,
    codepays: 'ET',
    nom: 'Ethiopie',
    indicatif: '251',
    devise: 2,
  },
  {
    id: 92,
    codepays: 'GE',
    nom: 'Géorgie',
    indicatif: '995',
    devise: 2,
  },
  {
    id: 93,
    codepays: 'GM',
    nom: 'Gambie',
    indicatif: '220',
    devise: 2,
  },
  {
    id: 94,
    codepays: 'GI',
    nom: 'Gibraltar',
    indicatif: '350',
    devise: 2,
  },
  {
    id: 95,
    codepays: 'GL',
    nom: 'Groenland',
    indicatif: '299',
    devise: 2,
  },
  {
    id: 96,
    codepays: 'GT',
    nom: 'Guatemala',
    indicatif: '502',
    devise: 2,
  },
  {
    id: 97,
    codepays: 'GN',
    nom: 'Guinée',
    indicatif: '224',
    devise: 2,
  },
  {
    id: 98,
    codepays: 'GY',
    nom: 'Guyana',
    indicatif: '592',
    devise: 2,
  },
  {
    id: 99,
    codepays: 'HT',
    nom: 'Haïti',
    indicatif: '509',
    devise: 2,
  },
  {
    id: 100,
    codepays: 'HN',
    nom: 'Honduras',
    indicatif: '504',
    devise: 2,
  },
  {
    id: 101,
    codepays: 'HK',
    nom: 'Hong Kong',
    indicatif: '852',
    devise: 2,
  },
  {
    id: 102,
    codepays: 'HU',
    nom: 'Hongrie',
    indicatif: '36',
    devise: 2,
  },
  {
    id: 103,
    codepays: 'IN',
    nom: 'Inde',
    indicatif: '91',
    devise: 2,
  },
  {
    id: 104,
    codepays: 'ID',
    nom: 'Indonésie',
    indicatif: '62',
    devise: 2,
  },
  {
    id: 105,
    codepays: 'IQ',
    nom: 'Iraq',
    indicatif: '964',
    devise: 2,
  },
  {
    id: 106,
    codepays: 'IS',
    nom: 'Islande',
    indicatif: '354',
    devise: 2,
  },
  {
    id: 107,
    codepays: 'IL',
    nom: 'Israël',
    indicatif: '972',
    devise: 2,
  },
  {
    id: 108,
    codepays: 'JP',
    nom: 'Japon',
    indicatif: '81',
    devise: 2,
  },
  {
    id: 109,
    codepays: 'JO',
    nom: 'Jordanie',
    indicatif: '962',
    devise: 2,
  },
  {
    id: 110,
    codepays: 'KG',
    nom: 'Kirghizistan',
    indicatif: '996',
    devise: 2,
  },
  {
    id: 111,
    codepays: 'KI',
    nom: 'Kiribati',
    indicatif: '686',
    devise: 2,
  },
  {
    id: 112,
    codepays: 'LB',
    nom: 'Liban',
    indicatif: '961',
    devise: 2,
  },
  {
    id: 113,
    codepays: 'LY',
    nom: 'Libye',
    indicatif: '218',
    devise: 2,
  },
  {
    id: 114,
    codepays: 'LI',
    nom: 'Liechtenstein',
    indicatif: '423',
    devise: 2,
  },
  {
    id: 115,
    codepays: 'MG',
    nom: 'Madagascar',
    indicatif: '261',
    devise: 2,
  },
  {
    id: 116,
    codepays: 'MY',
    nom: 'Malaisie',
    indicatif: '60',
    devise: 2,
  },
  {
    id: 117,
    codepays: 'MW',
    nom: 'Malawi',
    indicatif: '265',
    devise: 2,
  },
  {
    id: 118,
    codepays: 'MV',
    nom: 'Maldives',
    indicatif: '960',
    devise: 2,
  },
  {
    id: 119,
    codepays: 'MA',
    nom: 'Maroc',
    indicatif: '212',
    devise: 2,
  },
  {
    id: 120,
    codepays: 'MR',
    nom: 'Mauritanie',
    indicatif: '222',
    devise: 2,
  },
  {
    id: 121,
    codepays: 'MX',
    nom: 'Mexique',
    indicatif: '52',
    devise: 2,
  },
  {
    id: 122,
    codepays: 'MN',
    nom: 'Mongolie',
    indicatif: '976',
    devise: 2,
  },
  {
    id: 123,
    codepays: 'MZ',
    nom: 'Mozambique',
    indicatif: '258',
    devise: 2,
  },
  {
    id: 124,
    codepays: 'NP',
    nom: 'Népal',
    indicatif: '977',
    devise: 2,
  },
  {
    id: 125,
    codepays: 'NR',
    nom: 'Nauru',
    indicatif: '674',
    devise: 2,
  },
  {
    id: 126,
    codepays: 'NI',
    nom: 'Nicaragua',
    indicatif: '505',
    devise: 2,
  },
  {
    id: 127,
    codepays: 'SO',
    nom: 'Somalie',
    indicatif: '252',
    devise: 2,
  },
  {
    id: 128,
    codepays: 'SD',
    nom: 'Soudan',
    indicatif: '249',
    devise: 2,
  },
  {
    id: 129,
    codepays: 'LK',
    nom: 'Sri Lanka',
    indicatif: '94',
    devise: 2,
  },
  {
    id: 130,
    codepays: 'SE',
    nom: 'Suède',
    indicatif: '46',
    devise: 2,
  },
  {
    id: 131,
    codepays: 'CH',
    nom: 'Suisse',
    indicatif: '41',
    devise: 2,
  },
  {
    id: 132,
    codepays: 'AS',
    nom: 'Samoa américaines',
    indicatif: '684',
    devise: 2,
  },
  {
    id: 133,
    codepays: 'GU',
    nom: 'Guam',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 134,
    codepays: 'MP',
    nom: 'Mariannes du Nord',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 135,
    codepays: 'PA',
    nom: 'Panama',
    indicatif: '507',
    devise: 2,
  },
  {
    id: 136,
    codepays: 'TL',
    nom: 'Timor Oriental',
    indicatif: '670',
    devise: 2,
  },
  {
    id: 137,
    codepays: 'NL',
    nom: 'Pays-Bas',
    indicatif: '31',
    devise: 4,
  },
  {
    id: 138,
    codepays: 'PT',
    nom: 'Portugal',
    indicatif: '351',
    devise: 4,
  },
  {
    id: 139,
    codepays: 'RE',
    nom: 'Réunion',
    indicatif: '262',
    devise: 4,
  },
  {
    id: 140,
    codepays: 'SM',
    nom: 'Saint-Marin',
    indicatif: '378',
    devise: 4,
  },
  {
    id: 141,
    codepays: 'ZW',
    nom: 'Zimbabwe',
    indicatif: '263',
    devise: 10,
  },
  {
    id: 142,
    codepays: 'TD',
    nom: 'Tchad',
    indicatif: '235',
    devise: 5,
  },
  {
    id: 143,
    codepays: 'NO',
    nom: 'Norvège',
    indicatif: '47',
    devise: 2,
  },
  {
    id: 144,
    codepays: 'NC',
    nom: 'Nouvelle-Calédonie',
    indicatif: '687',
    devise: 2,
  },
  {
    id: 145,
    codepays: 'NZ',
    nom: 'Nouvelle-Zélande',
    indicatif: '64',
    devise: 2,
  },
  {
    id: 146,
    codepays: 'OM',
    nom: 'Oman',
    indicatif: '968',
    devise: 2,
  },
  {
    id: 147,
    codepays: 'UG',
    nom: 'Ouganda',
    indicatif: '256',
    devise: 2,
  },
  {
    id: 148,
    codepays: 'UZ',
    nom: 'Ouzbékistan',
    indicatif: '998',
    devise: 2,
  },
  {
    id: 149,
    codepays: 'PE',
    nom: 'Pérou',
    indicatif: '51',
    devise: 2,
  },
  {
    id: 150,
    codepays: 'PK',
    nom: 'Pakistan',
    indicatif: '92',
    devise: 2,
  },
  {
    id: 151,
    codepays: 'PG',
    nom: 'Papouasie-Nouvelle-Guinée',
    indicatif: '675',
    devise: 2,
  },
  {
    id: 152,
    codepays: 'PY',
    nom: 'Paraguay',
    indicatif: '595',
    devise: 2,
  },
  {
    id: 153,
    codepays: 'PH',
    nom: 'Philippines',
    indicatif: '63',
    devise: 2,
  },
  {
    id: 154,
    codepays: 'PL',
    nom: 'Pologne',
    indicatif: '48',
    devise: 2,
  },
  {
    id: 155,
    codepays: 'PF',
    nom: 'Polynésie française',
    indicatif: '689',
    devise: 2,
  },
  {
    id: 156,
    codepays: 'QA',
    nom: 'Qatar',
    indicatif: '974',
    devise: 2,
  },
  {
    id: 157,
    codepays: 'RO',
    nom: 'Roumanie',
    indicatif: '40',
    devise: 2,
  },
  {
    id: 158,
    codepays: 'GB',
    nom: 'Royaume-Uni',
    indicatif: '44',
    devise: 2,
  },
  {
    id: 159,
    codepays: 'RU',
    nom: 'Russie',
    indicatif: '7',
    devise: 2,
  },
  {
    id: 160,
    codepays: 'RW',
    nom: 'Rwanda',
    indicatif: '250',
    devise: 2,
  },
  {
    id: 161,
    codepays: 'WS',
    nom: 'Samoa',
    indicatif: '685',
    devise: 2,
  },
  {
    id: 162,
    codepays: 'SC',
    nom: 'Seychelles',
    indicatif: '248',
    devise: 2,
  },
  {
    id: 163,
    codepays: 'SL',
    nom: 'Sierra Leone',
    indicatif: '232',
    devise: 2,
  },
  {
    id: 164,
    codepays: 'AI',
    nom: 'Anguilla',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 165,
    codepays: 'SR',
    nom: 'Suriname',
    indicatif: '597',
    devise: 2,
  },
  {
    id: 166,
    codepays: 'SZ',
    nom: 'Swaziland',
    indicatif: '268',
    devise: 2,
  },
  {
    id: 167,
    codepays: 'SY',
    nom: 'Syrie',
    indicatif: '963',
    devise: 2,
  },
  {
    id: 168,
    codepays: 'TJ',
    nom: 'Tadjikistan',
    indicatif: '992',
    devise: 2,
  },
  {
    id: 169,
    codepays: 'TZ',
    nom: 'Tanzanie',
    indicatif: '255',
    devise: 2,
  },
  {
    id: 170,
    codepays: 'TO',
    nom: 'Tonga',
    indicatif: '676',
    devise: 2,
  },
  {
    id: 171,
    codepays: 'TN',
    nom: 'Tunisie',
    indicatif: '216',
    devise: 2,
  },
  {
    id: 172,
    codepays: 'TM',
    nom: 'Turkménistan',
    indicatif: '993',
    devise: 2,
  },
  {
    id: 173,
    codepays: 'TR',
    nom: 'Turquie',
    indicatif: '90',
    devise: 2,
  },
  {
    id: 174,
    codepays: 'TV',
    nom: 'Tuvalu',
    indicatif: '688',
    devise: 2,
  },
  {
    id: 175,
    codepays: 'UA',
    nom: 'Ukraine',
    indicatif: '380',
    devise: 2,
  },
  {
    id: 176,
    codepays: 'UY',
    nom: 'Uruguay',
    indicatif: '598',
    devise: 2,
  },
  {
    id: 177,
    codepays: 'VU',
    nom: 'Vanuatu',
    indicatif: '678',
    devise: 2,
  },
  {
    id: 178,
    codepays: 'VE',
    nom: 'Venezuela',
    indicatif: '58',
    devise: 2,
  },
  {
    id: 179,
    codepays: 'WF',
    nom: 'Wallis-et-Futuna',
    indicatif: '681',
    devise: 2,
  },
  {
    id: 180,
    codepays: 'YE',
    nom: 'Yémen',
    indicatif: '967',
    devise: 2,
  },
  {
    id: 181,
    codepays: 'ZM',
    nom: 'Zambie',
    indicatif: '260',
    devise: 2,
  },
  {
    id: 182,
    codepays: 'INTER',
    nom: 'International',
    indicatif: '0',
    devise: 2,
  },
  {
    id: 183,
    codepays: 'AG',
    nom: 'Antigua-et-Barbuda',
    indicatif: '12',
    devise: 2,
  },
  {
    id: 184,
    codepays: 'BS',
    nom: 'Bahamas',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 185,
    codepays: 'BB',
    nom: 'Barbade',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 186,
    codepays: 'BM',
    nom: 'Bermudes',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 187,
    codepays: 'DM',
    nom: 'Dominique',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 188,
    codepays: 'GD',
    nom: 'Grenade',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 189,
    codepays: 'JM',
    nom: 'Jamaïque',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 190,
    codepays: 'MS',
    nom: 'Montserrat',
    indicatif: '1997',
    devise: 2,
  },
  {
    id: 191,
    codepays: 'TT',
    nom: 'Trinité-et-Tobago',
    indicatif: '1997',
    devise: 2,
  },
];
