export const SEXE = [
  { libelle: 'Masculin', value: 'M' },
  { libelle: 'Feminin', value: 'F' },
  { libelle: 'Autre', value: 'A' },
];

export const LISTE_DEFAUT = [
  {
    nom: 'AKAKPO',
    prenom: 'Akofa',
    age: 15,
    dataNaissance: '01/02/2005',
    sexe: 'M',
    id: 1,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Teddy',
    age: 25,
    dataNaissance: '08/05/1995',
    sexe: 'M',
    id: 2,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Mariane',
    age: 30,
    dataNaissance: '04/09/1990',
    sexe: 'F',
    id: 3,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Akofa',
    age: 15,
    dataNaissance: '01/02/2005',
    sexe: 'M',
    id: 4,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Teddy',
    age: 25,
    dataNaissance: '08/05/1995',
    sexe: 'M',
    id: 5,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Mariane',
    age: 30,
    dataNaissance: '04/09/1990',
    sexe: 'F',
    id: 6,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Akofa',
    age: 15,
    dataNaissance: '01/02/2005',
    sexe: 'M',
    id: 7,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Teddy',
    age: 25,
    dataNaissance: '08/05/1995',
    sexe: 'M',
    id: 8,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Mariane',
    age: 30,
    dataNaissance: '04/09/1990',
    sexe: 'F',
    id: 9,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Akofa',
    age: 15,
    dataNaissance: '01/02/2005',
    sexe: 'M',
    id: 7,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Teddy',
    age: 25,
    dataNaissance: '08/05/1995',
    sexe: 'M',
    id: 8,
  },
  {
    nom: 'AKAKPO',
    prenom: 'Mariane',
    age: 30,
    dataNaissance: '04/09/1990',
    sexe: 'F',
    id: 9,
  },
];
